### ISSUE TITLE
rectAnnotation plus arrowhead doesn't get along

### ISSUE THREAD

**Issue by emeeks** [susielu/d3-annotation#12]
![screen shot 2017-03-07 at 2 22 03 pm](https://cloud.githubusercontent.com/assets/495634/23680851/92dbf2a8-0341-11e7-845a-7cd3bb0b2efd.png)

**Comment by emeeks** [comment]
This only happens when it's a straight line, the diagonal lines work just fine.

**Comment by susielu** [comment]
This should be resolved in the latest version 1.5.0
