### ISSUE TITLE
create example that uses d3-svg-annotation from npm with default d3v4 bundle

### ISSUE THREAD

**Issue by micahstubbs** [susielu/d3-annotation#13]
would be nice to have an example of using  d3-svg-annotation from npm on top of the default d3v4 bundle that you get when the `depedencies` from your `package.json` look like this: 

```
  "dependencies": {
    "d3": "^4.7.1",
    "d3-svg-annotation": "^1.10.0",
    "lodash": "^4.17.4"
  }
```

**Comment by micahstubbs** [comment]
purists may not like this approach, but this is the first thing I think of when I want to add annotations to a project that already uses the default bundle.

**Comment by Lacroute** [comment]
Doc and exemples from [here](http://d3-annotation.susielu.com/#introduction) aren't enough?
