### ISSUE TITLE
Plugin breaks in IE because of Object.assign

### ISSUE THREAD

**Issue by gabrielflorit** [susielu/d3-annotation#17]
IE doesn't support Object.assign: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility

What do you think of using something like `_.assign`?

**Comment by susielu** [comment]
I'll make an update, thanks for letting me know.

**Comment by susielu** [comment]
The latest version has been polyfilled and should work without Object.assign.
