### ISSUE TITLE
Wrapping and text size in responsive design

### ISSUE THREAD

**Issue by Mavromatika** [susielu/d3-annotation#19]
Hi, I'd like to thank you first of all for this wonderful plugin. I'm using it a lot now and I think it was very well designed. 
I'm currently struggling however with dynamic text wrapping and size in notes. I'm trying to make a chart responsive to the size of it parent. For this I resize and re-position a lot of elements on the window resize event. For my annotations to remain visible I need to change both the wrap length and the font size of the notes.

But the interaction between the wrapping function and the font-size is obscure to me. It seems like it's computing the line height based on the font-size it can find before displaying the annotations (which makes sense). But given that d3.js only allows us to change inline style properties of existing elements, one needs to draw the annotations once to be able to set their font size, before redrawing them with the new wrap length and position. 

At least this what I understand at the moment (after several hours trying to figure out a solution, so bear with me if what I wrote doesn't make sense). 

Would it be possible to define the font-size in the annotation data instead (in the note, in addition to wrap length) ? This way all dynamic changes are to be made in the annotations' data, and when the annotations are re-draw the note is properly displayed.

**Comment by susielu** [comment]
Thanks for the feedback. It is computing the line height based on the font-size. I hadn't thought of putting the font-size in the annotation data. 

I'll try to put together a small example to test out this case, let me know if you have anything like this put together already that I could use for testing. I'll let you know what conclusions I come to.

Thanks!

**Comment by susielu** [comment]
I believe this is fixed in the latest version 1.13.0 please let me know if you have any issues with the rendering positioning after upgrading.

Thanks,
Susie

**Comment by Mavromatika** [comment]
Thanks Susie, I'll give it a try will provide feedback here.

**Comment by manuelroth** [comment]
@susielu thank you very much for your example. It helped me a lot

**Comment by pablo-mayrgundter** [comment]
Hi Susie, I'm stuck too and just adjusted my code to work like you suggest, but to no avail.  I can't get my test label to wrap, using wrapSplitter, textWrap, etc.

https://observablehq.com/@pablo-mayrgundter/map-regional-with-click-callback

I'd appreciate any help!  Loving the annotation library :)
