### ISSUE TITLE
Note Label padding top different then padding

### ISSUE THREAD

**Issue by ivanbacher** [susielu/d3-annotation#21]
First of all nice plugin! 
I am having a issue with the positioning of the annotations. The problem seems to be that if `dy` is placed underneath `y`, then additional padding is added to to the label. Please see image below.

![screen shot 2017-04-18 at 15 39 47](https://cloud.githubusercontent.com/assets/5493114/25136710/a51aa914-244d-11e7-8136-f3330dee07cb.png)

I am assuming this has something to do with the line height property?

**Comment by susielu** [comment]
Thanks for the pic along with the post, I'll take a look in the next week.

**Comment by susielu** [comment]
I believe this is fixed in the latest version 1.13.0 please let me know if you have any issues with the rendering positioning after upgrading.

Thanks,
Susie
