### ISSUE TITLE
catch drag start/end event ?

### ISSUE THREAD

**Issue by lorenzopub** [susielu/d3-annotation#26]
hi susie,

thanks again for this awesome d3-plugin.

except if i miss something, there is no drag start/end events triggered in editMode.

is it something targeted in a future release ?

thanks in advance
Laurent

**Comment by susielu** [comment]
Hmmm I should be triggering those events in edit mode: https://github.com/susielu/d3-annotation/blob/master/src/Types-d3.js#L257

What is your use case? Maybe it's not being registered in the right way?

**Comment by lorenzopub** [comment]
i wanted to have access to the event like : .on('subjectover', ....,   .on( 'subjectclick', etc, ....

my use case is : after a drag event end , i want to catch the new dx/dy position and store it in my database with the annotation.
the work around i do is not efficient : i have a toggle button to switch editMode. when it's switch to false i do a loop on all annotations to see which one as changed then save it to the database

**Comment by susielu** [comment]
Ah okay do any of these events fit your use case? 
https://github.com/susielu/d3-annotation/blob/master/src/Adapter-d3.js#L20
You should be able to register an on subjectout but let me know if you run into issues with it.

**Comment by lorenzopub** [comment]
this is what i tried but it's not working, but maybe i do something wrong or missing  ;-)

**Comment by susielu** [comment]
Gotchaaaaa I'll take a look probably a bug on my end. Will let you know when I have an update.

**Comment by lorenzopub** [comment]
thanks cool susie

**Comment by susielu** [comment]
Hmm I am able to trigger the events even in editMode

Here's the relevant code, maybe it's a bug related to the setup you have are you using webpack? rollup? the direct script?

Example code: 
```
       const makeAnnotations = d3.annotation()
          .type(d3.annotationCalloutCircle)
          .annotations(annotations)
          .editMode(true)
          .on('subjectover', function(){
            console.log('subjectover', d3.event, d3.event.type)
          })
          .on('subjectout', function(){
            console.log('subjectout', d3.event, d3.event.type)
          })
          .on('noteover', function(){
            console.log('noteover', d3.event, d3.event.type)
          })
```

![over](https://cloud.githubusercontent.com/assets/1449837/26037585/0f6b9e74-38ab-11e7-9984-2a404d445442.gif)

**Comment by lorenzopub** [comment]
i use directly the plugin. but i just realise that my use case explanation was not clear.

in fact, my expectation is to have something like that :

.on('dragend',function(){
           //execute my code 
})


if i use
 .on('noteout', function(){
           //execute my code
})

it works but called each time i drag the anntotation

**Comment by susielu** [comment]
Ahhhh okay understood thanks for the clarification.

**Comment by susielu** [comment]
In the latest version 1.15.0 there are now dragstart and dragend events, let me know if you have any issues using it.

**Comment by lorenzopub** [comment]
hi susie,

i just tested and everything is fine & simplify my life  ;-)


thanks
