### ISSUE TITLE
bug end-connector change dynamically

### ISSUE THREAD

**Issue by lorenzopub** [susielu/d3-annotation#28]
hi susie,

i just found a bug with the end-connector :

after 1st setup, if i want to change the end-connector dynamically, the new end-connector is displayed but the old one is not removed.

1st setup : annotation.connector.end = 'dot';

....
annotation = makeAnnotations.annotations.collection().annotations[annotation_idx];
annotation.connector.end = 'arrow'
makeAnnotations.annotations.update();

![image](https://cloud.githubusercontent.com/assets/10477169/26273435/a576cd88-3d30-11e7-819f-6c539838493d.png)

**Comment by susielu** [comment]
I believe this is resolved in 1.17.0, let me know if you have any problems with it.

**Comment by lorenzopub** [comment]
it works when i switch between arrow & dot, but not if i switch to 'none'

**Comment by susielu** [comment]
This should be working now in `2.2.2`
