### ISSUE TITLE
IE11 bug after 1.13.0 release

### ISSUE THREAD

**Issue by russellgoldenberg** [susielu/d3-annotation#29]
Error:  Object doesn't support property or method 'draw'

https://github.com/susielu/d3-annotation/commit/75114013958f1baaddbcfc468dfb4ff9c34e9f29#diff-01ef6ddcd6013061bb6b63e7cf0bbf8fL3328

When I revert the line above to the previous version (without the `!d.type.name` ternary expression) it works.

**Comment by susielu** [comment]
I just published a new version 1.17.0 that changed the logic I was using in that ternary. Did that fix the IE bug?

**Comment by russellgoldenberg** [comment]
Yup! looks good on IE11 with 1.17.0
