### ISSUE TITLE
Not selecting annotations globally e.g., select ('g.annotations')

### ISSUE THREAD

**Issue by namwkim** [susielu/d3-annotation#31]
I am trying to have a separate annotator for each visualization. 

Currently, the edit mode is enabled globally. It would be nice if this can be modular. :)

**Comment by susielu** [comment]
You could have separate calls to d3.annotation to achieve this.

**Comment by namwkim** [comment]
You are right! awesome! It must have been my mistake. I initially thought it might be due to the line 74 in https://github.com/susielu/d3-annotation/blob/master/src/Handles.js
