### ISSUE TITLE
Annotation doesn't appear on IE 11

### ISSUE THREAD

**Issue by richielionell** [susielu/d3-annotation#32]
Hi Susie, When I open https://bl.ocks.org/susielu/a464c24d8b42f0c4d9fafe7b48e9e60a on IE11 it shows a blank page. The svg doesn't get formed.
![d3-annotations-ie-issue](https://user-images.githubusercontent.com/4058058/28023245-f32dc160-65aa-11e7-8f93-4b116fd0a6f1.png)

**Comment by briantjacobs** [comment]
+1

**Comment by susielu** [comment]
I'll update the example with the latest. Thanks!
