### ISSUE TITLE
Line wrapping with custom fonts

### ISSUE THREAD

**Issue by susielu** [susielu/d3-annotation#33]
If you are only supporting Chrome and Firefox, they implement the CSS font loading API. You can wrap all of your code in a fonts ready function: 

```js 
document.fonts.ready.then(function(){
  //write annotation code here
})
```

Otherwise I recommend using [Web Font Loader](https://github.com/typekit/webfontloader). I tried a simple example that worked the broken test case in Safari. 

Added webfont script to the page
```html
<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
```
then used their API to load the font and run code on the active event listener
```js
WebFont.load({
  google: {
     families: ['Lato:300,900'],
  },
  active: function () {
    //write annotation code here
  }
})

**Comment by KingStar0012** [comment]
![photo-1541877944-ac82a091518a](https://user-images.githubusercontent.com/91761209/136158755-ca7a303a-a1ad-4e23-ba8a-a900540e5afe.jpg)
fgsdfg

**Comment by KingStar0012** [comment]
dfadsfasdf
