### ISSUE TITLE
Annotation Background Color

### ISSUE THREAD

**Issue by yongpark** [susielu/d3-annotation#39]
Hi Susie,

Is there an easy way to add a background color to annotations to make it easier to read when the graph is cluttered? Or would that require appending a rectangle manually behind the annotation text itself? Using the CalloutCircle annotation type at the moment. Thanks.

Cheers,

Yong

**Comment by susielu** [comment]
There already is a rectangle behind the text available with the css accessor `rect.annotation-note-bg` is that what you're looking for?

**Comment by yongpark** [comment]
Exactly what I was looking for. Thanks!
