### ISSUE TITLE
Add drag to texts

### ISSUE THREAD

**Issue by Microbie** [susielu/d3-annotation#45]
Would it be easy to add the drag of the note to the texts as well so a user can use the handle as well as the texts to drag the note?
We are integrating your annotations in our mapping tool (Maps4News) and that has the paradigm that you can drag labels and we want to remain consistent

**Comment by susielu** [comment]
Hey there, was able to get a version with drag on text as well working locally. I'll publish it in the next day or so.

**Comment by susielu** [comment]
This has been added in 2.2.0

**Comment by Microbie** [comment]
Great! Thanks a lot!
