### ISSUE TITLE
The property `subject` don't work when config the annotation in version 2.2.2

### ISSUE THREAD

**Issue by wufeihuang** [susielu/d3-annotation#48]
I wanted to use the type `d3.annotationCalloutCircle`, and the configuration was like below, it partly worked, but the circle the `subject` described didn't show up, while there was no errors in the console. 
And then I tried other type like `d3.annotationCalloutRect`, also the same.
But when I changed the version to `2.2.0`, it workd without changing any other code.
So I guess there is some problem in this version of `2.2.2`.

```
const type = d3.annotationCalloutCircle

const annotations = [{
  note: {
    label: "Longer text to show text wrapping",
    title: "Annotations :)"
  },
  //can use x, y directly instead of data
  //data: { date: "18-Sep-09", close: 185.02 },
  x: 100,
  y: 100,
  dy: 137,
  dx: 162,
  subject: {
    radius: 50,
    radiusPadding: 5
  }
}]
```

**Comment by susielu** [comment]
Thanks for posting this, just pushed a fix to `2.2.3` let me know if you have any issues with it.

**Comment by wufeihuang** [comment]
@susielu Hi, I have tried the `2.2.3`, the `subject` works well, but _**the `note line` is missing**_.

![image](https://user-images.githubusercontent.com/12652891/38286524-6b344e34-37f8-11e8-80f7-40636e886ffa.png)

**Comment by susielu** [comment]
Ah you're right, it should be fixed now.
