### ISSUE TITLE
Overlapping Demo is broken

### ISSUE THREAD

**Issue by mcnuttandrew** [susielu/d3-annotation#49]
Not sure if this is the right place to raise this issue, but it appears that (on mac latest stable Chrome) the demo for @emeeks's Network Annotation with Collision Detection is broken. I raise this here, because that block appears to be part of the docs for this library.

![screen shot 2018-04-14 at 9 26 25 pm](https://user-images.githubusercontent.com/6854312/38774272-896f45fe-402a-11e8-8882-f9dd6dfe02f4.png)

**Comment by susielu** [comment]
Thanks for letting me know it looks like the resize example is also broken. I'll take a look.

**Comment by susielu** [comment]
@mcnuttandrew thanks for flagging this, in the latest version `2.2.5` it has been fixed.
