### ISSUE TITLE
Drag connector end when editMode is enabled

### ISSUE THREAD

**Issue by gabrieleciech** [susielu/d3-annotation#51]
Hi Susie, thank you for this awesome d3 plugin.
I was wondering if there's a way to update the position of the connector end when the editMode is enabled. As far as I can see it is possible to change the connector end position only for the connectors which type is `d3.annotationCalloutCircle`. Am I right or I am missing something?

If there is no such functionality could you please guide me in such a way that I can try to add it myself and then make a pull request?
Thanks

**Comment by susielu** [comment]
This is a bug, I'm taking a look now. Thanks for catching this.

**Comment by susielu** [comment]
This should be fixed in `v2.3.1`

**Comment by gabrieleciech** [comment]
Hi Susie, I have tested out the new release and now everything is working as expected. Thank you for your time and cooperation.
