### ISSUE TITLE
Missing Typescript type - notePadding()

### ISSUE THREAD

**Issue by avoerman** [susielu/d3-annotation#55]
It looks like notePadding() is missing in the Typescript type definition.

> annotation.notePadding() Change the overall notePadding, otherwise in the annotation object array you can change each individual one with the {note: {padding: 30}} property

I created a pull request to add the type here:

https://github.com/susielu/d3-annotation/pull/54

**Comment by susielu** [comment]
Thanks @avoerman and thanks for making the pull request, it is updated in `v2.3.2`
