### ISSUE TITLE
Type definitions: Typescript

### ISSUE THREAD

**Issue by 0xNacho** [susielu/d3-annotation#8]
Hi there!

First of all, congratulations for this amazing library! It looks so great.

We're thinking of adding this library as a dependency of [proteic](https://github.com/proteus-h2020/proteic).

Since proteic is built on Typescript, we would need the type definitions to add any third-party library. 

Any plans for adding such type definitions?

**Comment by samccone** [comment]
hi @0xNacho and @jorgeyp I have gone ahead and created a simple scaffold for us with most of the base Type  annotated 🐧  :)

I think we should be able to collab from here and flush it out more.

Thoughts?

**Comment by 0xNacho** [comment]
Hi @samccone . 

I'm starting a new branch (called d3-annotation) in proteic. 

After this initial type definition, I will try  to fully integrate d3-annotation into our library. I will use this issue for reporting all the missing types we find out.

**Comment by samccone** [comment]
boom no prob, going to work with @susielu to land this asap

Thanks for your help!!

**Comment by susielu** [comment]
Looks good thank you both for working on this!! \o/
